// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence that do not exceed the n-th
// term, find the sum of the even-valued terms.

function isEven(num) {
  return num % 2 === 0;
}

function fiboEvenSum(num) {
  let sum = 0;

  for (let i = 1, prev = 0, curr = 1; i <= num; i++) {
    const tempCurr = curr;
    curr += prev;
    prev = tempCurr;

    if (isEven(curr)) {
      sum += curr;
    }
  }

  return sum;
};

module.exports = fiboEvenSum;
